name: learn_bloc_advance
description: Learning Bloc with Clean Architecture


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.0
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.10.0
  # Remote API
  connectivity_plus: ^2.0.3
  http: ^0.13.4
  # Local cache
  shared_preferences: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
#  mockito: ^5.0.16
  mocktail: ^0.2.0

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


#  assets:



